name: Adriano Tanaka
markdown: redcarpet
pygments: true
github: https://www.github.com/exaem
Sobre: Administrador de banco de dados.
urls:
    - text: Github
      url: https://github.com/exaem
    - text: Contato
      url: mailto:adriano.tanakaa@gmail.com
