title: "Adriano Tanaka - Oracle e Linux"
author: "Adriano Tanaka"
description: "Um blog dedicado a Oracle e Linux"
#subheading: "Really cool blog about ... something"
more: "read more"
url: "http://tanakaa.github.io/"
#baseurl: "/tanakaa.github.com" # comment out if in root directory

comments:
    disqus: "adrianotanakablog"
#    isso: "comments.mysite.org"

style:
#    body: "whitesmoke"
    padding: 33%
    anchor: "#46f"
    serif-heading: true
    nav: "#181818"
#    headline: "#06f"
    description: "white"
    article:
        odd: "#ffffff"
        even: "#222222"

links:
  - github: "https://github.com/tanakaa/"
 # - twitter: "https://twitter.com/me/"
  - google-plus: "https://plus.google.com/+AdrianoTanakaa"
 # - reddit: "https://www.reddit.com/user/me/"
  - youtube: "https://www.youtube.com/user/adrianotanakaa"
 # - steam: "http://steamcommunity.com/id/me/"

excerpt_separator: "\n\n\n" ""
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]
