# Site settings
title: "Adriano Tanaka - Oracle e Linux"
autor: "Adriano Tanaka"
header-img: img/home-bg.jpg
email: adriano.tanakaa@gmail.com
description: "Um blog dedicado a Oracle e Linux"
baseurl: ""
url: "http://tanakaa.github.io/"
  
# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

excerpt_separator: "<!--more-->" 
defaults: [{scope: {path: ""}, values: {layout: "default"}}, {scope: {path: "", type: "posts"}, values: {comments: true}}]


comments:
disqus: "adrianotanakablog"

analytics :
  provider : google
  google : 
  tracking_id : 'UA-64236204-1'
