# Site settings
title: "Adriano Tanaka - Oracle e Linux"
autor: "Adriano Tanaka"
header-img: img/home-bg.jpg
email: your-email@yourdomain.com
description: "Um blog dedicado a Oracle e Linux"
baseurl: ""
url: "http://tanakaa.github.io/"


# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
